### ISSUE TITLE
many project not in, like envoy

### ISSUE THREAD

**Issue by V0idk** [k0kubun/gitstar-ranking#83] opened 2022-03-17 16:16 UTC

**Comment by k0kubun** [comment] 2022-03-17 16:57
This is a duplicate of a closed issue https://github.com/k0kubun/gitstar-ranking/issues/56. Please log into the website if you really want to fix it.

https://gitstar-ranking.com/envoyproxy/envoy

**Closed by k0kubun** 2022-03-17 16:57 UTC

**Comment by V0idk** [comment] 2022-03-18 06:17
> This is a duplicate of a closed issue #56. Please log into the website if you really want to fix it.
> 
> https://gitstar-ranking.com/envoyproxy/envoy

https://app.tooljet.com/applications/github-star-ranking 
https://github.com/EvanLi/Github-Ranking/


but this two site is normal , maybe you can crawler those missing repo

**Comment by k0kubun** [comment] 2022-03-18 06:36
Did you read my comment in the issue that I shared https://github.com/k0kubun/gitstar-ranking/issues/56#issuecomment-550496294? Note that we're indeed crawling users unlike when the comment was posted, but still, the fundamental issue, GitHub limiting the concurrency of API requests from this app, still persists. The current crawler would _eventually_ load users like envoyproxy too, but it's just taking a lot of time because of how GitHub works. The goal of my repository is different from other similar projects; I'm crawling all users. If you like those websites more, please just use them. Thank you.

**Comment by V0idk** [comment] 2022-03-18 09:12
> Did you read my comment in the issue that I shared [#56 (comment)](https://github.com/k0kubun/gitstar-ranking/issues/56#issuecomment-550496294)? Note that we're indeed crawling users unlike when the comment was posted, but still, the fundamental issue, GitHub limiting the concurrency of API requests from this app, still persists. The current crawler would _eventually_ load users like envoyproxy too, but it's just taking a lot of time because of how GitHub works. The goal of my repository is different from other similar projects; I'm crawling all users. If you like those websites more, please just use them. Thank you.

Hi, I am using the repositories ranking:  https://gitstar-ranking.com/repositories, 
but i don't understand your  "GitHub limiting ", 
we can search by language:XXX stars:>10 and sort by star,  like this: 

![image](https://user-images.githubusercontent.com/17514799/158973640-22e1638f-1527-400c-b078-f9861622dad0.png)

if we search all language and rearrange,  i think the ranking would not missing some repos

**Comment by k0kubun** [comment] 2022-03-18 16:20
I know. It simply doesn't crawl things that way. It just crawls users from id=1 to id=infinity. I get your idea because that's what I've already thought of long before, but I simply don't afford to work on that since this is just one of the repositories that I need to maintain and has a relatively lower priority than other projects. You may file a pull request to implement that though.
